# 基础离线评估配置文件
# 为所有评估模式提供通用配置

# 通用评估参数
common:
  device: 'cuda'  # 推理设备
  seed: 42        # 随机种子
  output_dir: 'outputs/evaluation'  # 评估结果输出目录
  save_results: True  # 是否保存评估结果
  verbose: True       # 是否显示详细日志

# 测试数据配置
test_data:
  root: '/root/robot/data/data/task1/lerobot'  # 数据根目录
  repo_id: 'task_400_episodes'  # 数据集ID
  episodes_range: [0, 50]       # 测试episodes范围 [start, end]
  batch_size: 1                 # 批处理大小（离线评估通常为1）
  num_workers: 4                # 数据加载进程数
  max_episodes: 10              # 最大测试episodes数
  max_steps_per_episode: 100    # 每个episode最大步数

# 基础评估指标
evaluation:
  # 动作精度指标
  action_metrics:
    - 'mse'         # 均方误差
    - 'mae'         # 平均绝对误差
    - 'cosine_sim'  # 余弦相似度
    - 'l2_norm'     # L2范数差异

  # 关节分析
  joint_analysis:
    enable: True
    joint_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  # 14关节权重
    critical_joints: [0, 1, 6, 7]  # 关键关节索引

  # 时序分析
  temporal_consistency:
    enable: True
    window_size: 5              # 时间窗口大小
    smoothness_penalty: 0.1     # 平滑度惩罚系数

  # 输出控制
  save_predictions: True        # 保存预测结果
  save_ground_truth: True       # 保存真实值
  generate_plots: True          # 生成可视化图表
  plot_frequency: 10            # 每N个episode生成一次图表

# 推理性能配置
performance:
  measure_inference_time: True  # 测量推理时间
  measure_memory_usage: True    # 测量内存使用
  inference_batch_size: 1       # 推理批大小
  warmup_steps: 5               # 预热步数

# 报告生成配置
report:
  format: ['json', 'csv']       # 报告格式
  include_plots: True           # 是否包含图表
  detailed_analysis: True       # 是否包含详细分析
  summary_only: False           # 是否只生成摘要

# 可视化配置
visualization:
  plot_action_comparison: True    # 绘制动作对比图
  plot_error_distribution: True   # 绘制误差分布图
  plot_temporal_trends: True      # 绘制时序趋势图
  save_format: 'png'              # 图片保存格式
  dpi: 300                        # 图片分辨率

# 日志配置
logging:
  level: 'INFO'                 # 日志级别
  save_logs: True               # 是否保存日志文件
  log_frequency: 100            # 每N步记录一次详细日志