hydra: # Hydra 配置文件保存目录，仅供参数检查使用
  run:
    dir: ./outputs/train_hydra_save/singlerun/${now:%Y%m%d_%H%M%S} # 单次运行目录
  sweep:
    dir: ./outputs/train_hydra_save/multirun/${now:%Y%m%d_%H%M%S} # sweep并行时的根目录
    subdir: ${hydra:job.override_dirname}

task: 'task_400_episodes' # 自定义任务名称
method: 'humanoid_hierarchical' # 自定义方法名称，区分分层架构
timestamp: ${now:%Y%m%d_%H%M%S} # 自动获取的运行时时间戳
episodes_to_use:
  - 0
  - 399 # 限制使用的episodes数量，[start, end]格式

repoid: 'lerobot/${task}'
root: '/mnt/e/robot/data/data/task1/lerobot/1-400' # 你的本地转换好的lerobot数据的目录（任务一数据）

# 训练相关配置
training:
  output_directory: 'outputs/train/${task}/${method}' # 模型参数保存路径
  seed: 42
  max_epoch: 500
  save_freq_epoch: 10
  log_freq: 1
  device: 'cuda'
  accumulation_steps: 1
  ema_power: 0.75

  batch_size: 64 # 分层架构使用稍小的batch size
  num_workers: 11
  drop_last: False

  max_training_step: null
  resume: False
  resume_timestamp: null

  # 数据增广相关的配置
  RGB_Augmenter:
    enable: True
    max_num_transforms: 1
    random_order: True
    tfs:
      notransform:
        weight: 2.0
        type: 'Identity'
        kwargs: {}
      brightness:
        weight: 1.0
        type: 'ColorJitter'
        kwargs: { 'brightness': [0.5, 1.5] }
      contrast:
        weight: 1.0
        type: 'ColorJitter'
        kwargs: { 'contrast': [0.5, 1.5] }

policy_name: humanoid_diffusion # 新的策略类型

policy:
  _target_: kuavo_train.wrapper.policy.diffusion.DiffusionConfigWrapper.CustomDiffusionConfigWrapper

  # 启用分层架构
  use_hierarchical: True

  # 基础diffusion参数（保持兼容）
  horizon: 16
  n_action_steps: 8
  drop_n_last_frames: 7

  normalization_mapping:
    RGB:
      _target_: lerobot.configs.types.NormalizationMode
      value: MEAN_STD
    DEPTH:
      _target_: lerobot.configs.types.NormalizationMode
      value: MIN_MAX

  # 图像处理
  crop_is_random: True
  crop_shape: [420, 560]
  use_amp: True

  # 视觉backbone（使用更轻量的）
  vision_backbone: resnet18
  use_separate_rgb_encoder_per_camera: False

  # diffusion settings
  noise_scheduler_type: DDPM
  num_train_timesteps: 100
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  beta_end: 0.02
  prediction_type: epsilon
  clip_sample: true
  clip_sample_range: 1.0
  num_inference_steps: null
  do_mask_loss_for_padding: false

  # optimizer and scheduler
  optimizer_lr: 0.0001
  optimizer_betas:
    - 0.95
    - 0.999
  optimizer_eps: 1.0e-08
  optimizer_weight_decay: 1.0e-03
  scheduler_name: cosine
  scheduler_warmup_steps: 500

  # 分层架构特有配置
  hierarchical:
    # 四层配置
    layers:
      safety:
        type: 'GRU'
        hidden_size: 64
        num_layers: 1
        input_dim: 16 # 手臂关节状态(双臂14维+手爪2维)，适配only_arm=true配置
        output_dim: 16 # 对应手臂控制输出
        response_time_ms: 10
        priority: 1
        enabled: True

      gait:
        type: 'Hybrid' # GRU + Transformer
        gru_hidden: 128
        gru_layers: 2
        tf_layers: 2
        tf_heads: 4
        tf_dim: 128
        horizon: 20
        priority: 2
        enabled: True

      manipulation:
        type: 'Transformer'
        layers: 3
        hidden_size: 512
        heads: 8
        dim_feedforward: 2048
        horizon: 100
        priority: 3
        enabled: True

      planning:
        type: 'Transformer'
        layers: 4
        hidden_size: 1024
        heads: 16
        dim_feedforward: 4096
        horizon: 500
        priority: 4
        enabled: True

    # 层权重配置
    layer_weights:
      safety: 2.0 # 安全层权重最高
      gait: 1.5 # 步态层次之
      manipulation: 1.0 # 操作层标准权重
      planning: 0.8 # 规划层权重较低

    # 任务特化配置
    task_specialization:
      enable: True
      modules: ['dynamic_grasping', 'weighing', 'placement', 'sorting']

    # 课程学习配置 - 支持任务特定训练
    curriculum_learning:
      enable: True
      # 传统通用课程学习（作为后备）
      universal_stages:
        stage1:
          name: 'safety_only'
          layers: ['safety']
          epochs: 50
          loss_threshold: 0.1
        stage2:
          name: 'safety_gait'
          layers: ['safety', 'gait']
          epochs: 100
          loss_threshold: 0.08
        stage3:
          name: 'safety_gait_manipulation'
          layers: ['safety', 'gait', 'manipulation']
          epochs: 150
          loss_threshold: 0.06
        stage4:
          name: 'full_hierarchy'
          layers: ['safety', 'gait', 'manipulation', 'planning']
          epochs: 200
          loss_threshold: 0.05

      # 任务特定训练模式
      task_specific:
        enable: True
        # 当前可用任务列表（动态更新）
        available_tasks: [1] # 目前只有任务1
        # 训练模式: "single_task", "progressive_multi_task", "concurrent_multi_task"
        training_mode: 'single_task'

        # 防遗忘配置
        anti_forgetting:
          enable: false # 单任务时关闭
          rehearsal_ratio: 0.0
          memory_buffer_size: 1000

        # 任务权重平衡
        task_balancing:
          strategy: 'complexity_based' # "equal", "complexity_based", "data_based"
          dynamic_adjustment: true

  custom: # 保持与原配置的兼容性
    # support depth image
    use_depth: True
    depth_backbone: resnet18 # 统一使用ResNet
    use_separate_depth_encoder_per_camera: False

    # resize and augmentation
    resize_shape: [210, 280]

    # state encoder
    use_state_encoder: True
    state_feature_dim: 128

    # 使用分层架构时禁用原有的transformer
    use_unet: False
    use_transformer: False # 由分层架构接管

# 任务特定训练配置
task_specific_training:
  enable: True
  # 数据路径配置（临时修改：只使用任务一数据）
  data_config:
    base_path: '/robot/data'
    task_directories:
      1: 'task-1/1-2000/lerobot' # 任务1：动态抓取（当前使用root配置）
      2: 'task-2/lerobot' # 任务2：称重（未来）
      3: 'task-3/lerobot' # 任务3：摆放（未来）
      4: 'task-4/lerobot' # 任务4：分拣（未来）

  # 当前训练阶段
  current_phase: 1

  # 训练策略
  training_strategy:
    # 渐进式学习：逐步添加新任务
    progressive_learning: True
    # 每阶段最小训练epochs
    min_epochs_per_phase: 100
    # 任务切换损失阈值
    phase_transition_loss_threshold: 0.08

  # 内存管理
  memory_management:
    # 限制同时加载的任务数据
    max_concurrent_tasks: 2
    # episode数量限制（避免内存溢出）
    max_episodes_per_task: 300
    # 数据预加载
    preload_data: True

  # 性能监控
  performance_monitoring:
    # 任务特定指标
    track_task_specific_metrics: True
    # 层性能分析
    layer_performance_analysis: True
    # 保存任务特定检查点
    save_task_checkpoints: True
