# VLA Transformer Config - 36维全身配置（包含腿部）
# 用于演示如何扩展到更多自由度

hydra:
  run:
    dir: ./outputs/train_hydra_save/singlerun/${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ./outputs/train_hydra_save/multirun/${now:%Y%m%d_%H%M%S}
    subdir: ${hydra:job.override_dirname}

task: 'task_vla_36dim'
method: 'vla_transformer_fullbody'
timestamp: ${now:%Y%m%d_%H%M%S}

episodes_to_use:
  - 0
  - 199

repoid: 'lerobot/${task}'
root: '/root/robot/data/fullbody/data/lerobot/' # 全身数据路径

training:
  output_directory: 'outputs/train/${task}/${method}'
  seed: 42
  max_epoch: 500
  save_freq_epoch: 10
  log_freq: 10
  device: 'cuda'
  accumulation_steps: 1
  ema_power: 0.75

  batch_size: 24 # 36维需要更多内存，减小batch size
  num_workers: 16
  drop_last: False

  test_training_mode: False
  test_training_epochs: 2
  max_training_step: null
  resume: False
  resume_timestamp: null

  scheduler_name: cosine
  scheduler_warmup_steps: 500

  RGB_Augmenter:
    enable: True
    max_num_transforms: 1
    random_order: True
    tfs:
      notransform:
        weight: 2.0
        type: 'Identity'
        kwargs: {}
      brightness:
        weight: 1.0
        type: 'ColorJitter'
        kwargs: { 'brightness': [0.5, 1.5] }
      contrast:
        weight: 1.0
        type: 'ColorJitter'
        kwargs: { 'contrast': [0.5, 1.5] }

policy_name: vla_transformer_fullbody

policy:
  _target_: kuavo_train.wrapper.policy.vla.VLAConfigWrapper

  # Token化配置
  patch_size: 16
  token_embed_dim: 512
  image_size: 224

  # Transformer配置（可以加深以处理更复杂的全身控制）
  transformer_depth: 10 # 增加深度
  transformer_heads: 8
  transformer_dim_feedforward: 2048
  transformer_dropout: 0.1

  # Diffusion Decoder配置
  num_denoiser_layers: 6 # 增加层数
  denoiser_heads: 8
  denoiser_dim_feedforward: 2048

  # Diffusion参数
  horizon: 16
  n_action_steps: 8
  n_obs_steps: 1
  drop_n_last_frames: 7

  num_train_timesteps: 100
  num_inference_steps: 50
  noise_scheduler_type: DDPM
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  beta_end: 0.02
  prediction_type: epsilon
  clip_sample: true
  clip_sample_range: 1.0
  do_mask_loss_for_padding: false

  # 优化器配置
  optimizer_lr: 0.0001
  optimizer_betas:
    - 0.95
    - 0.999
  optimizer_eps: 1.0e-08
  optimizer_weight_decay: 1.0e-03

  # 归一化配置
  normalization_mapping:
    RGB:
      _target_: lerobot.configs.types.NormalizationMode
      value: MEAN_STD
    DEPTH:
      _target_: lerobot.configs.types.NormalizationMode
      value: MIN_MAX
    STATE:
      _target_: lerobot.configs.types.NormalizationMode
      value: MIN_MAX
    ACTION:
      _target_: lerobot.configs.types.NormalizationMode
      value: MIN_MAX

  # State配置：36维全身（16维手臂 + 20维腿部）
  state_config:
    joints:
      # ==================== 左臂（7自由度）====================
      - {
          idx: 0,
          type: 'shoulder',
          side: 0,
          id: 0,
          name: 'left_shoulder_pitch',
        }
      - { idx: 1, type: 'shoulder', side: 0, id: 1, name: 'left_shoulder_roll' }
      - { idx: 2, type: 'shoulder', side: 0, id: 2, name: 'left_shoulder_yaw' }
      - { idx: 3, type: 'elbow', side: 0, id: 3, name: 'left_elbow_pitch' }
      - { idx: 4, type: 'wrist', side: 0, id: 4, name: 'left_wrist_yaw' }
      - { idx: 5, type: 'wrist', side: 0, id: 5, name: 'left_wrist_pitch' }
      - { idx: 6, type: 'wrist', side: 0, id: 6, name: 'left_wrist_roll' }

      # 左手爪（1自由度）
      - { idx: 7, type: 'gripper', side: 0, id: 7, name: 'left_gripper' }

      # ==================== 右臂（7自由度）====================
      - {
          idx: 8,
          type: 'shoulder',
          side: 1,
          id: 8,
          name: 'right_shoulder_pitch',
        }
      - {
          idx: 9,
          type: 'shoulder',
          side: 1,
          id: 9,
          name: 'right_shoulder_roll',
        }
      - {
          idx: 10,
          type: 'shoulder',
          side: 1,
          id: 10,
          name: 'right_shoulder_yaw',
        }
      - { idx: 11, type: 'elbow', side: 1, id: 11, name: 'right_elbow_pitch' }
      - { idx: 12, type: 'wrist', side: 1, id: 12, name: 'right_wrist_yaw' }
      - { idx: 13, type: 'wrist', side: 1, id: 13, name: 'right_wrist_pitch' }
      - { idx: 14, type: 'wrist', side: 1, id: 14, name: 'right_wrist_roll' }

      # 右手爪（1自由度）
      - { idx: 15, type: 'gripper', side: 1, id: 15, name: 'right_gripper' }

      # ==================== 左腿（10自由度）====================
      - { idx: 16, type: 'hip', side: 0, id: 16, name: 'left_hip_yaw' }
      - { idx: 17, type: 'hip', side: 0, id: 17, name: 'left_hip_roll' }
      - { idx: 18, type: 'hip', side: 0, id: 18, name: 'left_hip_pitch' }
      - { idx: 19, type: 'knee', side: 0, id: 19, name: 'left_knee_pitch' }
      - { idx: 20, type: 'ankle', side: 0, id: 20, name: 'left_ankle_pitch' }
      - { idx: 21, type: 'ankle', side: 0, id: 21, name: 'left_ankle_roll' }
      - { idx: 22, type: 'ankle', side: 0, id: 22, name: 'left_toe_pitch_1' }
      - { idx: 23, type: 'ankle', side: 0, id: 23, name: 'left_toe_pitch_2' }
      - { idx: 24, type: 'ankle', side: 0, id: 24, name: 'left_toe_pitch_3' }
      - { idx: 25, type: 'ankle', side: 0, id: 25, name: 'left_toe_pitch_4' }

      # ==================== 右腿（10自由度）====================
      - { idx: 26, type: 'hip', side: 1, id: 26, name: 'right_hip_yaw' }
      - { idx: 27, type: 'hip', side: 1, id: 27, name: 'right_hip_roll' }
      - { idx: 28, type: 'hip', side: 1, id: 28, name: 'right_hip_pitch' }
      - { idx: 29, type: 'knee', side: 1, id: 29, name: 'right_knee_pitch' }
      - { idx: 30, type: 'ankle', side: 1, id: 30, name: 'right_ankle_pitch' }
      - { idx: 31, type: 'ankle', side: 1, id: 31, name: 'right_ankle_roll' }
      - { idx: 32, type: 'ankle', side: 1, id: 32, name: 'right_toe_pitch_1' }
      - { idx: 33, type: 'ankle', side: 1, id: 33, name: 'right_toe_pitch_2' }
      - { idx: 34, type: 'ankle', side: 1, id: 34, name: 'right_toe_pitch_3' }
      - { idx: 35, type: 'ankle', side: 1, id: 35, name: 'right_toe_pitch_4' }

  # 图像和训练配置
  use_depth: True # 使用深度图像
  use_amp: True # 使用混合精度训练
